[project]
name = "vnpt-track2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
developer = []
development = [
    "datasets>=4.4.1",
    "ipywidgets>=8.1.8",
    "jupyterlab>=4.5.0",
]
